name: Laravel Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Change this to your PHP version

    - name: Install dependencies
      run: |
        composer install --no-dev --optimize-autoloader

    - name: Configure environment
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Set permissions
      run: |
        sudo chown -R www-data:www-data storage bootstrap/cache
        sudo chmod -R 775 storage bootstrap/cache

    - name: Deploy to Vultr
      run: |
        # Add your deployment script or commands here
        # Example: ssh into the server and pull the latest changes
        ssh your_username@your_server_ip 'cd /path/to/yourlaravelrepo && git pull origin main'

    - name: Restart web server
      run: sudo service nginx restart  # Change this based on your web server

